[build]
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

# Redirect www to non-www when domain is connected
[[redirects]]
  from = "https://www.immaculatestarsacademy.com/*"
  to = "https://immaculatestarsacademy.com/:splat"
  status = 301
  force = true
